# Generated by Django 3.0.8 on 2020-10-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonModel',
        ),
    ]
