# Generated by Django 3.0.8 on 2020-10-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201005_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
        migrations.AddField(
            model_name='club',
            name='name1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='name2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='name3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
